# Site settings
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "guiialmeiida.github.io" 

# User settings
username: Guilherme Almeida
user_description: Atualmente analista de sistemas, estudante de programação e apaixonado por tecnologia.
user_title: Software Developer
email: gui.almeidacrz@gmail.com
twitter_username: _GuiiAlmeiida_
github_username:  guiialmeiida


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
