# Site settings
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "guiialmeiida.github.io" 

# User settings
username: Guilherme Almeida
user_description: Desenvolvedor desde 2019, com experiência em Java, JQuery, React, React Native, atualmente trabalhando com Javascript, Typescript, NodeJS e AWS e adquirindo conhecimento em desenvolvimento IOS com a linguagem Swift.
user_title: Software Developer
email: gui.almeidacrz@gmail.com
twitter_username: _GuiiAlmeiida_
github_username:  guiialmeiida


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
